name: Docker

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:

  dispatch:
    strategy:
      matrix:
        repo: ["aweps/demo","slaystack/mono"]

    name: Dispatch
    runs-on: ubuntu-latest
    steps:

     - name: Repository Dispatch
       uses: peter-evans/repository-dispatch@1708dda5703a768a0fb0ef6a7a03a0c3805ebc59
       with:
         token: ${{ secrets.PA_TOKEN }}
         repository: ${{ matrix.repo }}
         event-type: dependency_update
         client-payload: '{ "github": ${{ tojson(github) }}}'


