name: Docker

on:
  schedule:
    - cron: "45 3 * * *"
  push:
    branches: [ master ]

jobs:

  synctags:

    name: Sync Tags
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PA_TOKEN }}

